---
# Install PostgreSQL on `db` hosts and restore databases from appropriate dumps
- hosts: db
  become: yes
  vars_files:
    - inventory/vars.yml
  roles:
    - ansible-role-postgresql

- post_tasks:
  - name: Download and restore database dumps
    block:
      - name: Download database dumps
        get_url:
          url: "{{ pg_dumps_servername }}/{{ item.value }}"
          dest: /tmp/
      - name: restore databases
        postgresql_db:
          name: "restore {{ item.key }}"
          state: restore
          target: "/tmp/{{ item.value }}"
      with_items: pg_dumps
